### ISSUE TITLE
Fields do not match input Google Sheet for one record

### ISSUE THREAD

**Issue by gjlawran** [okfn/datacatalogs.org#41]
The values displayed on the front-end for this record  http://datacatalogs.org/catalog/alabama
do not correctly map for Issued & License values
 Issued = Active, License = US/en

Couldn't find another record with a  similar issue.

**Comment by mattfullerton** [comment]
@gjlawran Thanks for spotting this. It was due to less frequently empty field(s) being empty which caused a shift in the rows. Shouldn't happen again, but I still need to fix formatting for cases of missing country, language and licenses (not a big task, but I'm working with occasional free minutes on this...!)
